DFE-Digital/fh-services

- .github/workflows/build-upload-artifact.yml
- .github/workflows/deploy-service.yml
- .github/workflows/deploy.yml
Rejigging a few small things about the pipeline.
---
Pipeline run: https://github.com/DFE-Digital/fh-services/actions/runs/10057883102
---
Effects of the changes:
- We can redeploy an older release up to the retention period of the artifacts, because they are no longer instantly deleted at the end of the pipeline.
- Fewer secrets and vars per environment. We now have per environment 3 secrets (for Azure connection) and 1 var (described below), everything else required for the services to function is in KeyVault
- `app-name` needed to be generic in `deploy.yml`, so I added a new environment variable that is just the resource prefix of Azure (e.g., `s181d01`), and then decided to compute the rest of the names of things (SQL server, resource group, keyvault) instead of storing them as …
> FHG-5471 : Update to the Pipeline

- .github/workflows/build-and-test-template.yml
- .github/workflows/build-and-test.yml
This PR updates the names of the `build-and-test.yml` and `build-and-test-template.yml` jobs to be in-line with the deployment jobs.
Pipeline run: https://github.com/DFE-Digital/fh-services/actions/runs/10094360231
> Update Names of Matrix Jobs (Main)

- .github/actions/variable-substitution/action.yml
- .github/workflows/deploy-service.yml
- src/ui/connect-dashboard-ui/src/FamilyHubs.RequestForSupport.Web/appsettings.json
- src/ui/connect-ui/src/FamilyHubs.Referral.Web/appsettings.json
- src/ui/idam-maintenance-ui/src/FamilyHubs.Idams.Maintenance.UI/appsettings.json
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/appsettings.json
This PR solves an issue where some keys are overwritten because they aren't in the KV but are in the appsettings, but when investigated by myself and @stevesatdfe we discovered that those values are not secret and are the same across all services, or simply aren't used anywhere in the code (EventGridUrl and Blob Storage stuff for example) so have been added into the appsettings and/or removed from the variable transform instead.
It also adds the keys in for analytics as they were missed in the original KV secret populating
Also skips installing entity framework if DB migrations don't have to be applied (the UIs) as an easy low hanging fruit tweak
> Pipeline Tweaks for Deployment

- .github/actions/variable-substitution/action.yml
Technically this is set up such that when the clarity tags are added to KeyVault they will just be picked up on the next deployment, but we wouldn't actually want this for the connection requests made release so I've set it to an empty string for this release, mirroring what we did on ADO but for GitHub deployments.
> FHB-45 : Revert ClarityId in Connection Requests Made

- .github/actions/variable-substitution/action.yml
- src/ui/connect-ui/src/FamilyHubs.Referral.Web/appsettings.json
- src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/appsettings.json
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/appsettings.json
This PR allows the app substitution to read the clarity IDs from KeyVault for each UI and add it to its appsettings
> FHB-45 : Add ClarityId to Substitution

- src/ui/connect-dashboard-ui/src/FamilyHubs.RequestForSupport.Web/appsettings.json
- src/ui/connect-ui/src/FamilyHubs.Referral.Web/appsettings.json
This PR reverts changes to the signout URL in the appsettings for connect and the connect dashboard, as they failed to redirect with the new URLs.
> FHB-543 : Hotfix to Revert Appsettings

- src/ui/connect-ui/src/FamilyHubs.Referral.Core/ApiClients/OrganisationClientService.cs
Ticket: [FHB-537](https://dfedigital.atlassian.net/browse/FHB-537)
---
This PR enables VCFS services to be shown on the Connect results page if they are inside a Family Hub, alongside services that aren't.
[FHB-537]: https://dfedigital.atlassian.net/browse/FHB-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-537 : Show VCFS Services in Connect if they are within a Family Hub

- .github/workflows/deploy.yml
---
Since Dev, Test & Prod are now all matched at S3 plan - which has much more CPU & RAM than S1, we can enable parallel deployments on the pipeline again.
> CI : Enable Parallel Deployments

- .github/workflows/deploy.yml
Bringing the `release-clarity-content` branch up to date with `main`
---
We already did a `main` -> `release-clarity-content` merge after we merged the connection requests made branch into `main` last week, so this change is only for the updated CI/CD pipeline, as now all App Service Plans are S3 tier so we can run the deployments in parallel.
---
Linked merge PR: https://github.com/DFE-Digital/fh-services/pull/54
> Merge `main` into `release-clarity-content` (2024/08/20)

- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/ServicesTemp.cs
Quick PR to add the `ServicesTemp` entity to the Shared Kernel, as both `service-directory-api` and `open-referral-function` use it.
> FHB-87 : Move Component to Shared Kernel

- src/ui/idam-maintenance-ui/src/FamilyHubs.Idams.Maintenance.Core/ApiClient/ServiceDirectoryClient.cs
I guess at some point we switched from deploying Debug builds to Release builds (Might have been me) but the code was broken on Release builds.
Really I don't know why this cache exists at all, who cares if the maintenance UI is slow?
> [FHB-552] Don't use cache when it's not enabled

- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Accessibility.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Address.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Attribute.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Contact.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/CostOption.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Funding.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Language.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Location.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/MetaTableDescription.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Metadata.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Organization.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/OrganizationIdentifier.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Phone.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Program.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/RequiredDocument.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Schedule.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Service.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/ServiceArea.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/ServiceAtLocation.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Taxonomy.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/TaxonomyTerm.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Repository/OpenReferralDbContextExtension.cs
Ticket: [FHB-548](https://dfedigital.atlassian.net/browse/FHB-548)
---
This ticket is part of FHB-548. It creates the entities and the basic table mappings. I have tested this migration locally and it works.
Foreign key relationships will be handled as part of FHB-549 and so a further update to the shared kernel and another migration will be created for that.
The `[JsonIgnore]` properties also reflect what is returned in the schema, and mean that the service we get from the mock API deserializes into a fully embedded Service (implementation of this is also apart of 549).
[FHB-548]: https://dfedigital.atlassian.net/browse/FHB-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-548 : Shared Kernel

- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Repository/OpenReferralDbContextExtension.cs
Ticket: [FHB-549](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/FHB/boards/245?selectedIssue=FHB-549)
Related Ticket: [FHB-548](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-548)
--
This PR fixes an issue originating on `FHB-548` where the names of the tables aren't plurals. The Service Directory API will create a migration for this fix in a separate PR, as it needs to use the package first.
[FHB-549]: https://dfedigital.atlassian.net/browse/FHB-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FHB-548]: https://dfedigital.atlassian.net/browse/FHB-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-549 : Fix Table Naming into Shared Kernel

- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Repository/OpenReferralDbContextExtension.cs
Ticket: [FHB-549](https://dfedigital.atlassian.net.mcas.ms/jira/software/projects/FHB/boards/245?selectedIssue=FHB-549)
Related Ticket: [FHB-548](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-548)
--
PR for the core tables: https://github.com/DFE-Digital/fh-services/pull/115
--
This PR fixes an issue originating on `FHB-548` where the names of the tables aren't plurals. The Service Directory API will create a migration for this fix in a separate PR, as it needs to use the package first. 
In this case, the many-to-many tables for Attributes & Metadata were not being automatically generated as plurals, so I've manually added it.
The tables will be in the forms:
- AccessibilityAttributes
- ServiceAttributes
- ContactAttributes
- ...
---
- AccessibilityMetadata
- ServiceMetadata
- …
> FHB-549 : Fix Table Naming into Shared Kernel (Continued)

- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Repository/OpenReferralDbContextExtension.cs
Accidentally had `PhoneMetadata` be called `ProgramMetadata`, which then conflicted with the actual `ProgramMetadata`. Have ensured that was the only error :)
> FHB-549 : Fix Duplicate Table Name

- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/TaxonomyTerm.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Repository/OpenReferralDbContextExtension.cs
Ticket: [FHB-549](https://dfedigital.atlassian.net/browse/FHB-549)
This PR fixes a minor bug with the OR Schema in which `TaxonomyTerm` has a "Version" column, but neither the database schema or JSON schema has it.
Another PR will be made from the Service Directory API to generate the migration for this fix after this is merged.
---
Database Schema:
---
JSON Schema:
[FHB-549]: https://dfedigital.atlassian.net/browse/FHB-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-549 : Remove Extra Column from Schema

- src/function/open-referral-function/src/FamilyHubs.OpenReferral.Function/FamilyHubs.OpenReferral.Function.csproj
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/FamilyHubs.ServiceDirectory.Data.csproj
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20240923115745_RemoveVersionColumnFromDedsTaxonomyTerms.Designer.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20240923115745_RemoveVersionColumnFromDedsTaxonomyTerms.cs
Ticket: [FHB-549](https://dfedigital.atlassian.net/browse/FHB-549)
Related PR: https://github.com/DFE-Digital/fh-services/pull/124
---
This PR adds the migration to remove the "Version" column from `[deds]` as explained in https://github.com/DFE-Digital/fh-services/pull/124, and updates the OR Function to use the same version.
[FHB-549]: https://dfedigital.atlassian.net/browse/FHB-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-549 : Migration to Remove Version Column

- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Core/Models/UrlKeys.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Delete-Service-Error.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Delete-Service-Error.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Detail.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/appsettings.json
This PR is adding in the Error page for when there are still open services.
- Add error page that will be used when there are no open connections.
- Added app settings to point to the other connect service on 1 of the links
Note:
-  Added dashboardweb url to general keyvaults
> Fhb 671 delete service error page

- src/shared/referral-shared/src/FamilyHubs.ReferralService.Shared/Dto/OrganisationDto.cs
- src/shared/referral-shared/src/FamilyHubs.ReferralService.Shared/FamilyHubs.ReferralService.Shared.csproj
Ticket: [FHB-680](https://dfedigital.atlassian.net/browse/FHB-680)
---
This PR updates the Referral Shared library to no longer have the ReferralServiceId in the OrganisationDto, as the database Organisation object no longer has a ReferralServiceId and so this will always be null going forward.
[FHB-680]: https://dfedigital.atlassian.net/browse/FHB-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-680 : Referral Shared

- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml.cs
Ticket: [FHB-735](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-735)
---
FHB-735 removes the check for open connection requests when the page loads, so it only checks once the user has clicked "Confirm" after saying "Yes" to wanting to delete the service.
[FHB-735]: https://dfedigital.atlassian.net/browse/FHB-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-735 : Check for Con. Req. only on Confirm

- src/service/referral-api/src/FamilyHubs.Referral.Api/Endpoints/MinimalReferralEndPoints.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/Endpoints/MinimalServiceEndPoints.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Detail.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Detail.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml.cs
Ticket: [FHB-669](https://dfedigital.atlassian.net/browse/FHB-669)
Ticket: [FHB-670](https://dfedigital.atlassian.net/browse/FHB-670)
---
This PR enables functionality for VCS Manager + VCS Dual Role to delete services. It also makes sure that only VCS users can see the warning on the delete service page.
Note: `RoleGroups.AdminRole` == `"DfEAdmin,LaManager,LaDualUser,VcsManager,VcsDualRole"`
[FHB-669]: https://dfedigital.atlassian.net/browse/FHB-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FHB-670]: https://dfedigital.atlassian.net/browse/FHB-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-669 / FHB-670 : VCS Manager + VCS Dual Role Delete

- terraform/modules/fhinfrastructurestack/main.tf
As part of FHB-731, I did not give GitHub enough perms on key vault as I tried to be specific rather than copying ADO account perms. It turns out that it does need some of the more obscure perms to remove resources from key vault. This PR adds all the same perms as ADO.
> FHB-731: Give GitHub account the same perms as the ADO account

- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service-error.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service-shutter.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml.cs
Ticket: [FHB-673](https://dfedigital.atlassian.net/browse/FHB-673)
---
When a VCS user tries to delete a service that has open connection requests, they get an error redirect because the error page for this scenario is gated with authorisation for LA users.
This ticket updates the role to be the correct one, and on top of this gates the other pages on the delete journey to keep a consistent pattern.
[FHB-673]: https://dfedigital.atlassian.net/browse/FHB-673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-673 : Fix Open Con. Req. Redirect Error

- src/Directory.Packages.props
References to the NuGet packages for FamilyHubs.Notification.* packages still exist in src/Directory.Packages.props even though we’ve moved to using project references.
> FHB-785: Remove NuGet references to FamilyHubs.Notification.*

- terraform/modules/fhinfrastructurestack/main.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-830
Added rule group override for 931130 (REQUEST-931-APPLICATION-ATTACK-RFI) to allow users to enter http and https URLs
> FHB-830: Added rule group override for 931130

- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Detail.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml.cs
Ticket: [FHB-675](https://dfedigital.atlassian.net/browse/FHB-675)
---
This PR:
- Enables DfE Admin users to see the delete link, which allows them to delete a service
- Refactors the delete page to show the open connection request warning dependent on Service Type instead of Role, as `FamilySharing` are services that only show up on Find, and are also only LA services (which can't have connection requests), whilst `InformationSharing` are services that only show up on Connect, and are also only VCFS services (which can have connection requests).
- Saves some performance by only checking for open connection requests if the service type is `InformationSharing` (aka a VCFS service), since as mentioned above LA services can't ever have connection requests against them.
[FHB-675]: …
> FHB-675 : DfE Admin can delete LA & VCFS Services

- src/SuperSolution.sln
- src/service/idam-api/src/FamilyHubs.Idam.Api/Controllers/UserSessionController.cs
- src/service/idam-api/src/FamilyHubs.Idam.Core/Commands/Delete/DeleteExpiredUserSessionsCommand.cs
- src/service/idam-api/tests/FamilyHubs.Idam.Api.UnitTests/ControllerTests/WhenPostCreateUserSession.cs
- src/service/idam-api/tests/FamilyHubs.Idam.Api.UnitTests/FamilyHubs.Idam.Api.UnitTests.csproj
Difficult to diagnose issue as the sessions are deleted as soon as someone else successfully logs in.
The theory is that the service was able to post a new session with the same SID as one that already existed. As the error only seems to occur in the morning, it's possible that it's old expired sessions.
This update is to ensure expired ones are removed first before attempting a new one.
Monitoring app insights after this goes in can tell us if it's working or not.
> FHB-842:  login bug

- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Core/Queries/Services/GetServices/GetServicesCommand.cs
The query to get servicesis pointing to the scheduled table to get the service deliveries. This is correct in that this table should be being used IF it's previous migrations and implementation was complete, which is has not been. SO we can point to the ServiceDeliveries table for now and look at switching it back over later.
Verified that the query now returns the same number of results with all 3 filters and without any.
> FHB-833:  list of services connect

- .gitignore
We don't want any of the files that are auto-generated when a developer uses the `docker-compose.yml` file in here showing up in git.
> Ignore local/db/sql folder

- local/db/docker-compose.yml
Docker containers now live under a parent called 'Family Hubs'
> Change docker container name

- src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/ServiceFilter/_Service.cshtml
Ticket: [FHB-712](https://dfedigital.atlassian.net/browse/FHB-712)
---
This PR:
- Fixes an issue the WAF flagged where there is a double encoding with the space character when the postcode has a space in it, e.g., the pre-encoded %20 became %2520 (as the % sign has ASCII %25) and this made the WAF sad, so it's now fully decoded before being re-encoded.
[FHB-712]: https://dfedigital.atlassian.net/browse/FHB-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FHB-712 : Fix Double URL Encoding

- src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/ServiceFilter/_Service.cshtml
Fix an issue with the margin being removed from an old element by adding it to the h3 header of the service link. Produces the same effect.
> FHB-908:  margin

- .github/workflows/build-and-test-template.yml
- .github/workflows/build-and-test.yml
This PR:
- Adds a test report summary to the job output for each project that is built & tested
- Adds `--configuration Release` to the build and test stages as it's the recommended practice when running unit tests
Example: https://github.com/DFE-Digital/fh-services/actions/runs/11836091576?pr=239
> CI : Add Test Reporter

- .github/workflows/deploy.yml
A flag to the deployment pipeline to allow testers to choose to reset and reseed databases as there is a valid use case for not doing it, if for example, they want to retest a ticket with a fix but don't want to re-create data they had previously created whilst testing.
> Add flag to reset and reseed databases

- src/service/referral-api/acceptance-tests/FamilyHubs.Referral.Api.AcceptanceTests/Configuration/ConfigAccessor.cs
- src/service/referral-api/acceptance-tests/FamilyHubs.Referral.Api.AcceptanceTests/FamilyHubs.Referral.Api.AcceptanceTests.csproj
- src/service/referral-api/acceptance-tests/FamilyHubs.Referral.Api.AcceptanceTests/Fixtures/BearerTokenGenerator.cs
- src/service/referral-api/acceptance-tests/FamilyHubs.Referral.Api.AcceptanceTests/README.md
- src/service/referral-api/acceptance-tests/FamilyHubs.Referral.Api.AcceptanceTests/appsettings.json
- src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Configuration/ConfigAccessor.cs
- src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/FamilyHubs.Report.Api.AcceptanceTests.csproj
- src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Fixtures/BearerTokenGenerator.cs
- src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/README.md
- src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/appsettings.json
- src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Configuration/ConfigAccessor.cs
- src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests.csproj
- src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/README.md
- src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/appsettings.json
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/Extensions/StartupExtensions.cs
> FHB-969  acceptance tests KV

- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/FamilyHubsUi/FamilyHubsLayoutModel.cs
- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/FamilyHubsUi/Options/FamilyHubsUiOptions.cs
- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/FamilyHubsUi/Options/IFamilyHubsUiOptions.cs
- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/Layout/ViewStart.cs
- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/Pages/Shared/_Head.cshtml
- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/Pages/Shared/_Layout.cshtml
After noticing the `"Error: "` prefix to the tab titles sometimes hung around on unrelated pages, myself and @Top-Cat quickly got it sorted - just needed to move the Error functionality outside of FamilyHubsUiOptions as it seems to be static and update the models on some of the other pages accordingly.
> FHB-117 : Fix Static Page

- src/service/idam-api/src/FamilyHubs.Idam.Api/StartupExtensions.cs
- src/service/idam-api/src/FamilyHubs.Idam.Api/web.config
- src/service/mock-hsda-api/src/FamilyHubs.Mock-Hsda.Api/Program.cs
- src/service/mock-hsda-api/src/FamilyHubs.Mock-Hsda.Api/web.config
- src/service/notification-api/src/FamilyHubs.Notification.Api/Endpoints/MinimalNotifyEndPoints.cs
- src/service/notification-api/src/FamilyHubs.Notification.Api/StartupExtensions.cs
- src/service/notification-api/src/FamilyHubs.Notification.Api/web.config
- src/service/referral-api/src/FamilyHubs.Referral.Api/Endpoints/MinimalReferralEndPoints.cs
- src/service/referral-api/src/FamilyHubs.Referral.Api/Endpoints/MinimalUserAccountEndPoints.cs
- src/service/referral-api/src/FamilyHubs.Referral.Api/StartupExtensions.cs
- src/service/referral-api/src/FamilyHubs.Referral.Api/web.config
- src/service/report-api/src/FamilyHubs.Report.Api/Endpoints/MinimalAdminReportEndPoints.cs
- src/service/report-api/src/FamilyHubs.Report.Api/Endpoints/MinimalOrgReportEndPoints.cs
- src/service/report-api/src/FamilyHubs.Report.Api/Program.cs
- src/service/report-api/src/FamilyHubs.Report.Api/web.config
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/Endpoints/MinimalLocationEndPoints.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/Endpoints/MinimalOrganisationEndPoints.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/Endpoints/MinimalServiceEndPoints.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/Endpoints/MinimalTaxonomyEndPoints.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/Properties/launchSettings.json
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/StartupExtensions.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/web.config
Using web.config means we can actually remove the Server header but doesn't work with Kestrel (which I use locally due to not being on windows) but should be fine in Azure.
> feat(APIs): Remove IIS headers. Add security headers

- .github/actions/database-migration/action.yml
- .github/workflows/deploy-service.yml
- .github/workflows/deploy.yml
- terraform/modules/fhinfrastructurestack/fh-report-api-app.tf
- terraform/modules/fhinfrastructurestack/fh-report-stg-api-app.tf
- terraform/modules/fhinfrastructurestack/main.tf
- terraform/modules/fhinfrastructurestack/open-referral-func.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-831
- Enable Entra admin on each SQL server in terraform
- Fix pipeline key vault variable name
- Add connection strings via terraform for each app
- Created SQL scripts that can be found in Confluence: https://dfedigital.atlassian.net/wiki/spaces/FHGUW/pages/4934598660/SQL+Server+App+Permission+Scripts
- Populated new pipeline connection strings for GitHub in each environment ahead of time - GitHub needs more perms to execute required migrations
- Left existing secrets for connection strings in place until after merging into all environments
- EntraId now allows developers to connect with SSMS or other tools (except ADS as BYOD blocks it) so devs do not need to use username/passwords - all devs are admins still via a group - …
> feat(config): Enable app database connectivity using EntraId

- terraform/modules/fhinfrastructurestack/open-referral-func.tf
Worked out why each plan was seeing a change to the open referral function. Need to move the setting to site config in a dedicated variable now as the previous process is deprecated and was trying to merge it automatically.
> chore(terraform): Fix annoying plan change for the open referral

- src/service/mock-hsda-api/src/FamilyHubs.Mock-Hsda.Api/Program.cs
- src/service/report-api/src/FamilyHubs.Report.Api/Program.cs
- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/Security/SecurityHeaders.cs
- src/ui/connect-dashboard-ui/src/FamilyHubs.RequestForSupport.Web/StartupExtensions.cs
- src/ui/connect-ui/src/FamilyHubs.Referral.Web/StartupExtensions.cs
- src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/StartupExtensions.cs
- src/ui/idam-maintenance-ui/src/FamilyHubs.Idams.Maintenance.UI/StartupExtensions.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/StartupExtensions.cs
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1114
- Remove http redirects
- Add strict dynamic for scripts instead of unsafe inline
The above addresses odd redirect behaviour that was causing the gateway to resolve the backend over https and also allows GA/Clarity to load scripts
> FHB-1114: Fix https redirect and GA/Clarity loading

- .github/workflows/run-e2e-tests.yml
Noticed the Playwright test uses half the number of cores on the CPU by default when parallelising its tests. This is usually to make sure there are free resources left for other things the user may want to be doing with their system.
However in our case the entire purpose of the runner is to run these tests, so we can speed it up (mainly Manage atm but this will scale better as more and more tests are added to both UIs) by telling it to use all of the cores of the runner (`nproc` is a Linux command that returns the number of CPU cores)
With Optimisation (2m 56s):
Without Optimisation (6m 8s):
> ci(playwright): Performance Optimisation

- src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.IntegrationTests/BaseTest.cs
- src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.IntegrationTests/Services/BaseServiceTest.cs
- src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.IntegrationTests/Services/WhenAddingAService.cs
- src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.IntegrationTests/Services/WhenEditingAService.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Journeys/ServiceJourneyPageExtensions.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Shared/LocationPageModel.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Shared/ServicePageModel.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Locations-For-Service.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Locations-For-Service.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Remove-Location.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Select-Location.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Detail.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Detail.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Time-Details-At-Location.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/What-Language.cshtml
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/times-at-location.cshtml.cs
Fixes the issue from the ticket where the persisted change value causes the back button to loop into the edit flow again rather than back out to the service list.
Also fixed the same loop occurring when saving instead of clicking back out of a change.
ALSO fixed another issue where triggering a validation error within a change flow would cause the app to lose track of where you are.
ALSO ALSO fixed another issue where triggering a validation error on "Extra availability details" would just return "Sorry, there is a problem with the service"
Finally fixed going back from manage location pages to manage service pages. (ie Manage service > Add or remove locations > Add location > Add new location > Back > Back > ERROR)
----
Plus some refactoring to make the next page code very slightly …
> [FHB-856] Fix flow bugs

- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250114141038_updateDedsSchema.Designer.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250114141038_updateDedsSchema.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Converters/StringToNullableTypeConverter.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/CostOption.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Location.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Organization.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Phone.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Schedule.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Service.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/TaxonomyTerm.cs
- src/shared/shared-kernel/tests/fh-shared-kernel.unit-tests/OpenReferral/Converters/WhenUsingStringToNullableTypeConverter.cs
Fix a couple of issues with the deds schema. With the updates we can ingest international v3
Update schema to account for some nullable fields to match international schema. The fields are also not in our MVD. This includes a database migration from entitiy framework.
Added a custom JSON deserlalizer to handle empty strings in the JSON. This is because the schema uses strings for all except numbers.
> FHB-1238 - Bug/deds schema update bug

- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Config/OrganisationConfiguration.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250117130759_SetOrganisationCreatedNotNull.Designer.cs
- src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250117130759_SetOrganisationCreatedNotNull.cs
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1237
Set the Organisation table Created column as not nullable as it will cause issues with the ADF given that the staging table does not allow nulls for the same column.
> chore: Set organisation created date as not nullable

- .github/workflows/build-and-test-template.yml
- .github/workflows/build-and-test.yml
- .github/workflows/build-upload-artifact.yml
- .github/workflows/deploy.yml
- .github/workflows/sonarcloud.yml
Noticed the package cache for NuGet hasn't been working the whole time. The cache isn't thread safe, so when multiple runners (e.g., PR build & test, or building artifacts before deploying) are using it, none of them can properly write to it and quickly break, which means that most of them were just grabbing their packages from NuGet instead of the cache and not being sped up.
Unfortunately the `hashFiles()` function only works relative to the root of the repository so you can't hash files specific to a project easily. As such the workaround is to add the name of the project into the cache to give each project its own cache.
Since the SonarCloud runs from the SuperSolution it also has its own special cache key.
Also technically it's SpatiaLite and not Spatialite so I just corrected that …
> ci: Fix Package Cache

- docs/arch/ADR001-use-http-for-inter-service-comms.md
- docs/arch/ADR002-use-a-managed-azure-database.md
- docs/arch/ADR004-use-aspdotnet-identity-auth.md
- docs/arch/ADR006-redis-for-session-storage.md
- docs/arch/ADR007-use-azure-app-services.md
- docs/arch/ADR008-use-govuk-one-login-auth.md
- docs/arch/ADR010-sql-server-caching.md
- docs/arch/ADR012-pull-data-from-external-orgs.md
- docs/arch/ADR013-ingest-into-staging-schema.md
- docs/arch/ADR020-create-mock-api-to-stub-las.md
- docs/arch/ADR025-use-sonar-cloud.md
- docs/arch/README.md
- docs/arch/TEMPLATE.md
Adds a new 'adr' folder to the in-repository documentation. Contains the ADRs from confluence 
which were assessed as architectural decisions -- not technical decisions or decisions about
service scope.
The remaining decisions will be archived unless I'm otherwise directed.
> Migrate ADRs to repository format

- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/FamilyHubsUi/Options/Configure/FamilyHubsUiOptionsConfigure.cs
- src/shared/web-components/tests/FamilyHubs.SharedKernel.Razor.UnitTests/FamilyHubsUi/Configure/FamilyHubsUiOptionsConfigureTests.cs
- src/shared/web-components/tests/FamilyHubs.SharedKernel.Razor.UnitTests/FamilyHubsUi/Configure/Helpers/FamilyHubsUiOptionsTestBase.cs
Ticket: [FHB-1188](https://dfedigital.atlassian.net/browse/FHB-1188)
---
This PR:
- Fixes an issue where when logging in as a VCFS user with the Connect Dashboard turned off, you would still have one tab as expected but it would be the "My Requests" one instead of "Search for a Service". This happened because the UI generates each permutation of the navigation tabs on startup to cater for each user type, and VCFS users swap the ordering and so using the 1st tab wasn't sufficient. I have updated the comment above the logic that does this to actually explain it.
[FHB-1188]: https://dfedigital.atlassian.net/browse/FHB-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Connect): FHB-1188 - VCFS User still sees "My Requests" Tab

- src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Search.cshtml
Ticket: [FHB-1247](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1247)
---
This PR:
- Fixes the screen reader on the postcode search page (specifically the text box). It never worked in Connect, but it did in Find, so I've just copied over the code from there. Tested it by running prod Find & this branch locally at the same time with a screen reader running and ensuring they were reading the same things when tabbing over the postcode search field.
[FHB-1247]: https://dfedigital.atlassian.net/browse/FHB-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Connect): FHB-1247 - Postcode Search Text Box Screen Reader

- src/Directory.Packages.props
- src/function/open-referral-function/src/FamilyHubs.OpenReferral.Function/Functions/TriggerPullServicesWebhook.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/Factories/SanitizerFactory.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/Services/Sanitizers/StringSanitizer.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/Utilities/ProfanityChecker.cs
- src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/Utilities/PropertyInspector.cs
- src/shared/shared-kernel/tests/fh-shared-kernel.unit-tests/Services/SanitizerTests.cs
- src/shared/shared-kernel/tests/fh-shared-kernel.unit-tests/Utilities/ProfanityCheckerTests.cs
The list of words is not exhaustive so will not catch 100%, all profanity words that are default can be viewed in the library. https://www.nuget.org/packages/Profanity.Detector
The library itself does extensive unit testing so the one in this PR is just to ensure it is plugged in.
UPDATE:
Introduced a method to check properties that is re usable, and I fixed an issue with the string sanitizer where it was not checking on List type properties
> feat: FHB-71 Profanity check

- terraform/modules/fhinfrastructurestack/main.tf
Redirection of find to connect was adding a redundant forward slash on the redirect URL. Cases:
https://dev.find-support-for-your-family.education.gov.uk -> https://dev.connect-families-to-support.education.gov.uk//
https://dev.find-support-for-your-family.education.gov.uk/ -> https://dev.connect-families-to-support.education.gov.uk//
https://dev.find-support-for-your-family.education.gov.uk/terms-and-conditions -> https://dev.connect-families-to-support.education.gov.uk//terms-and-conditions
Test on an incognito browser as the double-slash effect is sticky if done once.
> FHB-1173 Remove redundant forward slash being added to connect redirects.

- test/manage-e2e-tests/playwright.config.ts
- test/manage-e2e-tests/tests/auth.setup.ts
- test/manage-e2e-tests/tests/helpers.ts
- test/manage-e2e-tests/tests/serenity-tools/questions/login-questions.ts
Fixed manage tests issues.
1) we were asserting that we were on the /welcome page however GA appends a lot of gibberish on the url (https://test.manage-family-support-services-and-accounts.education.gov.uk/Welcome?_gl=1*17ss6kf*_up*MQ..*_ga*MjY0MjE0ODk0LjE3Mzg3NzYxMzc.*_ga_2VRSHGP9CY*MTczODc3NjEzNi4xLjAuMTczODc3NjEzNi4wLjAuMA..) so I changed the assertion to a question that check the URL contains baseURL + welcome.
2) Tests are reaching timeout, I think it's because we are using xpaths instead of data test ids. Upped the timeout slightly and ran the tests a few times - something to keep an eye on.
Tests running locally
Tests running in pipeline 
Note: find tests are failing I suspect due to find connect merge - will investigate separately.
> test: Fixed flaky e2e test

- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/Pages/ManageOrganisations.cshtml.cs
Ticket: [FHB-1330](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1330)
---
Fixes a bug in Manage where DfE Admins can add VCFS Organisations but LA Admins (Manager/Dual Role) cannot.
This was because the "Add Organisation" link inside the Manage Organisation page reset the LA Org Id. This is fine for DfE Admins as their first page is "Which LA is this organisation in?" which then promptly sets the Org Id in the cache again. However LA Admins already have their LA Org Id pre-set and so clearing it here will make it empty/null with no way to set it again, therefore they would see a "Sorry something went wrong" page when trying to add an org.
[FHB-1330]: https://dfedigital.atlassian.net/browse/FHB-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
> fix(Manage): FHB-1330 - LA Admin Users Cannot Add Organisations

- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/DeleteUser.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/Edit.cshtml.cs
Redirect back to the user list instead of throwing an error when a user can't be found.
The reported way to trigger this error is navigating back after deleting a user. We can't show the deletion screen anymore but I also wouldn't expect to see an error as the user hasn't done anything "wrong".
> [FHB-653] Fix something went wrong error when navigating back after deleting a user

- src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Areas/AccountAdmin/ManagePermissions/EditRolesTests.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/EditRoles.cshtml.cs
Calling the email service when old role and new role are equal causes it to throw an error as there's no template for that.
Just short circuiting the whole thing in this case and showing the success message.
> [FHB-1002] Don't send an email when permissions have not been changed

- terraform/modules/fhinfrastructurestack/alerting.tf
3 alerts: Server Errors, Total CPU Time, HTTP Response Time spread over 11 app services. Function app doesn't support CPUTime metric, so 32 alerts in total.
> FHB-1241 app service alerts

- terraform/modules/fhinfrastructurestack/alerting.tf
Removed alerts for the open_referral_mock_api_web_app and fh_idam_maintenance_ui app services after discussion with Dami, Aaron and Tina. They are usually switched off and the mock api is for internal testing.
> FHB-1421 removed alerts for the open_referral_mock_api_web_app and fh_idam_maintenance_ui app services

- terraform/envs/test2/env.tfvars
- terraform/main.tf
- terraform/modules/fhinfrastructurestack/alerting.tf
- terraform/modules/fhinfrastructurestack/vars.tf
- terraform/vars.tf
ADF doesn't exist for Test2 and may not exist for test environments in the future. Treat it as optional for alert creation.
> FHB-1242 adf alerts - treat the Azure Data Factory component as optional

- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/FeatureFlags/AlsoFilter.cs
- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/FeatureFlags/EnabledFilter.cs
- src/ui/connect-ui/src/FamilyHubs.Referral.Web/Program.cs
- src/ui/connect-ui/src/FamilyHubs.Referral.Web/appsettings.json
Add feature filters to conditionally apply dashboard filter. Also added a dummy filter to allow us to maintain easy on/off switching.
This will require changing the configuration names in key vault:
> CONNECT-UI-FeatureManagement--ConnectDashboard
> CONNECT-UI-FeatureManagement--ConnectDashboard--EnabledFor--0--Parameters--Value
> CONNECT-UI-FeatureManagement--VcfsServices
> CONNECT-UI-FeatureManagement--VcfsServices--EnabledFor--0--Parameters--Value
> [FHB-1250] Disable the request for support flag when vcfs flag is disabled

- src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
Ticket: [FHB-1335](https://dfedigital.atlassian.net/browse/FHB-1335)
---
This PR:
- Defaults to the string "None provided" on the "Extra availability details" sections of locations and other schedules (online and/or telephone) if no details were provided when adding the service.
[FHB-1335]: https://dfedigital.atlassian.net/browse/FHB-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(Connect): FHB-1335 - None Provided Default

- .github/actions/run-dotnet-stryker/action.yml
- .github/actions/run-dotnet-stryker/stryker-config.json
- .github/workflows/stryker-full-report.yml
- src/service/referral-api/tests/FamilyHubs.ReferralApi.FunctionalTests/BaseWhenUsingOpenReferralApiUnitTests.cs
- src/service/referral-api/tests/FamilyHubs.ReferralApi.FunctionalTests/CustomWebApplicationFactory.cs
- src/service/referral-api/tests/FamilyHubs.ReferralApi.FunctionalTests/ServiceDirectoryFactory.cs
- src/service/referral-api/tests/FamilyHubs.ReferralApi.FunctionalTests/WhenUsingReferralsApiUnitTests.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/Pages/ManageOrganisations.cshtml.cs
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Components/SortHeaderComponent.razor
- src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Components/SortOrder.cs
Ticket: [FHB-875](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-875)
Currently some config is default. For example the high/low/break at thresholds (80/60/0). This is because the scores are pretty dire at the moment and so we will need to analyse these and determine what values suit us later. This will influence the PR gating ticket also.
Example: https://github.com/DFE-Digital/fh-services/actions/runs/13509189310
---
This PR:
- Creates a new workflow to run DotNet Stryker on a weekly schedule against each project. It can also be ran manually in the Actions tab on GitHub.
- Bundles the critical section (i.e., running Stryker itself) into a reusable Action. This makes things a bit tidier but also can be reused for the ticket to implement Stryker PR gating. 
- Uses a central config …
> ci(Stryker): FHB-875 - Stryker Mutator Weekly Report

- test/find-e2e-tests/.gitignore
- test/find-e2e-tests/playwright.config.ts
- test/find-e2e-tests/tests/auth.setup.ts
- test/find-e2e-tests/tests/serenity-tools/find-questions.ts
Ticket: [FHB-1295](https://dfedigital.atlassian.net/browse/FHB-1295)
---
This PR:
- Adds basic auth login / session storage for the Single Directory. Should login make its return it's also set up to automatically work.
Workflow: https://github.com/DFE-Digital/fh-services/actions/runs/13569301824
As seen here Find is able to run its tests against Dev which currently has the basic auth gate enabled. The Manage tests are also executing meaning they are also continuing to work without modification.
[FHB-1295]: https://dfedigital.atlassian.net/browse/FHB-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(Playwright): Basic Auth for Single Directory

- src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferResultsPartialViews/_ResultsSection.cshtml
Adding test data id tag for services within the service search page to help automated tests.
> FHB-1174-Adding-Testdata-id-tag-for-services

- src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/Pages/Shared/_Head.cshtml
- src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/Index.cshtml
This PR...
- Adds a special case for the home page of a site to have its name in the tab just once by matching the H1 tag.
- This changes the home page tab of Connect from `Find support for parents, carers and young people - Find support for parents, carers and young people - GOV.UK` to just `Find support for parents, carers and young people`
- Also bonus fixes Manage, which used to say `Manage family support services and accounts - Manage family support services and accounts - GOV.UK` to just say `Manage family support services and accounts`.
- Other pages still retain the old pattern as expected. E.g., `Search for services by postcode - Find support for parents, carers and young people - GOV.UK`
Ticket: [FHB-1433](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1433)
[FHB-1433]: …
> refactor(Connect): FHB-1433 - Home Page Title

- terraform/files/dashboard/template.json
- terraform/modules/fhinfrastructurestack/alerting.tf
Dashboard UI has been merged with Connect, so remove the corresponding report item from the monitoring dashboard. 
Change the alerts resource group to the usual group (s181*-family-hubs) for preprod and prod. Attempted to reuse the s181*-silverHubs alerts-specific resource group which is managed by the central azure team, but some resource tags are defined by policy causing Terraform to apply needless updates to every alert. Example:
~ resource "azurerm_monitor_metric_alert" "app-gateway-backend-last-byte-response-time-alert" {
id                       = "/subscriptions/***/resourceGroups/s181p02-silverMonitor/providers/Microsoft.Insights/metricAlerts/s181p02-fh-appgw-sd-ui-backend-last-byte-response-time-alert"
name                     = …
> FHB-1437 Remove dashboard UI from monitoring dashboard and change alerting resource group

- terraform/modules/fhinfrastructurestack/alerting.tf
This PR removes the Azure alerts for the find service. Specifically those alerts related to the find app service and gateway backend, since find has now been merged with connect.
> FHB1391 - remove find app service alerts and find gateway back-end specific alerts
