DFE-Digital/fh-services

.github/workflows/build-upload-artifact.yml, .github/workflows/deploy-service.yml, .github/workflows/deploy.yml
Copying the new pipeline changes to the release branch to sync it with `main` =]
=> FHG-5471 : Update to the Pipeline Sync

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Select-Location-Content-Bottom.cshtml, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Select-Location.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Description-Content.cshtml, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Detail.cshtml, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/add-location-content.cshtml
Copied from https://github.com/DFE-Digital/fh-service-directory-admin-ui/pull/414
=> FHB-438:  Manage - small updates off the back of content audit

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Errors/PossibleErrors.cs
Copied changes from now-closed https://github.com/DFE-Digital/fh-referral-ui/pull/309 for @EladTrebor
=> FHB-437: Connect small changes off the back of content audit

.github/actions/variable-substitution/action.yml
Re-add stub auth and claims variable replacement
=> FHB-544: Bug fix to add variable substitution for stub auth and claims

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Time-Details-At-Location.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/times-at-location.cshtml.cs
Ticket: [FHB-534](https://dfedigital.atlassian.net/browse/FHB-534)
---
This PR removes the checks for availability days being populated or the extra availability description being filled in for a location, so that you can add or edit the location of a service and save those changes in the check details page.
[FHB-534]: https://dfedigital.atlassian.net/browse/FHB-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-534 : Fix Save Button not Displaying on Location Edit

.github/workflows/deploy.yml
Added test 2 so we can deploy the stub into the test 2 environment
=> Added test 2 so we can deploy the stub into the test 2 environment

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/privacy/Index.cshtml, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Privacy.cshtml
Ticket: [FHB-42](https://dfedigital.atlassian.net/browse/FHB-42)
---
This ticket addresses changes requested by the testers in regards to the privacy policy pages
[FHB-42]: https://dfedigital.atlassian.net/browse/FHB-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-42 : Changes to Privacy Policy

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/CheckDetails.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Confirmation.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ContactByPhone.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ContactDetails.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ContactMethods.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ContactMethodsContent.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/SupportDetails.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Telephone.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Text.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/WhySupportContent.cshtml
Copying https://github.com/DFE-Digital/fh-referral-ui/pull/310 by @EladTrebor to the Mono Repo
---
Updating 'the service' to 'this service' on the make a connection request journey
Consistency across service
Updating copy across the connection request journey 
See prototype pages for comparison 
(https://dfedigital.atlassian.net/jira/software/projects/FHB/boards/245?selectedIssue=FHB-437)
=> FHB-437: Connection request journey ('the' to 'this')

src/service/mock-hsda-api/src/FamilyHubs.Mock-Hsda.Api/FamilyHubs.Mock-Hsda.Api.csproj, src/service/mock-hsda-api/src/FamilyHubs.Mock-Hsda.Api/Tests/Family Hubs - Mock HSDA.postman_collection.json, src/service/mock-hsda-api/src/FamilyHubs.Mock-Hsda.Api/Tests/Family Hubs Mock HSDA API.postman_environment.json
Added the Postman Collection to cover the existing stub endpoints
=> FHB-89 postman collection

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/La/PersonsDetails.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/La/SubjectAccessResultDetails.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Welcome.cshtml
Could also just delete this, we can always recover from git.
=> [FHB-559] Hide subject access request

src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Builders/Http/HttpClientFactory.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Builders/Http/HttpRequestBuilder.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/FamilyHubs.Report.Api.AcceptanceTests.csproj, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Fixtures/BearerTokenGenerator.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/GlobalUsings.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Tests/Steps/ServiceSearchesForAnLaOrgSteps.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Tests/Steps/ServiceSearchesOverallSteps.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Tests/Steps/SharedSteps.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Tests/Stories/ApiInfoTests.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Tests/Stories/ConnectionRequestLaOrgTests.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Tests/Stories/ConnectionRequestTests.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Tests/Stories/ServiceSearchesForAnLaOrgTests.cs, src/service/report-api/acceptance-tests/FamilyHubs.Report.Api.AcceptanceTests/Tests/Stories/ServiceSearchesOverallTests.cs
- Move tests to XUnit from the mixed NUnit and XUnit
- Clean up a few warnings
=> FHB-605: Refactor tests to use XUnit and a few cleanups of warnings

src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/Enumerable/EnumerableExtensions.cs, src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj, src/shared/shared-kernel/tests/fh-shared-kernel.unit-tests/Enumerable/EnumerableExtensionsTests.cs, src/shared/shared-kernel/tests/fh-shared-kernel.unit-tests/FamilyHubs.SharedKernel.UnitTests.csproj, src/ui/connect-ui/src/FamilyHubs.Referral.Core/ApiClients/OrganisationClientService.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Core/ConnectTelemetryPiiRedactor.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Core/FamilyHubs.Referral.Core.csproj, src/ui/connect-ui/src/FamilyHubs.Referral.Core/Helper/EnumerableExtensions.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Core/ValidationAttributes/UKGdsPostcodeAttribute.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Core/ValidationAttributes/UKGdsTelephoneNumberAttribute.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Infrastructure/FamilyHubs.Referral.Infrastructure.csproj, src/ui/connect-ui/src/FamilyHubs.Referral.Web/FamilyHubs.Referral.Web.csproj, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferDetail.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferDetail.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferResults.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/Shared/ProfessionalReferralCacheModel.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/Shared/ProfessionalReferralModel.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingOrganisationClientService.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingEmail.cs
Also includes:
* update Sonar and fix new warnings
=> FHB-606 Display service schedules

docs/hsds-3_0-er-diagram.md, docs/hsds-3_0-er-diagram.mermaid, util/README.md
Adds an HSDS entity relationship diagram, and links to it from the README.
=> Add HSDS ER Diagram docs

.github/workflows/deploy.yml
https://dfedigital.atlassian.net.mcas.ms/browse/FHB-488
- Added Test2 so it is available for this branch to deploy into the test 2 environment
=> FHB-488: Add Test2 as an option for deployment

src/Directory.Packages.props, src/ui/connect-ui/src/FamilyHubs.Referral.Web/FamilyHubs.Referral.Web.csproj, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/FamilyHubs.ServiceDirectory.Admin.Web.csproj
https://dfedigital.atlassian.net.mcas.ms/browse/FHB-589
- Reduced the IdentityModel packages to 7.7.1
=> FHB-589: Fix dotnet 8 upgrade

src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Builders/Http/HttpRequestBuilder.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Builders/Http/HttpRequestClient.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Builders/Http/HttpRequestFactory.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Builders/IBuilder.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Configuration/ConfigAccessor.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Configuration/ConfigModel.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests.csproj, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Models/ServiceSearchRequest.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Models/ServiceSearchResponse.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Models/ServiceSearchResults.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/README.md, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Tests/Steps/ApiInfoSteps.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Tests/Steps/ServiceSearchSteps.cs, src/service/service-directory-api/acceptance-tests/FamilyHubs.ServiceDirectory.Api.AcceptanceTests/Tests/Stories/ApiInfoTests.cs
- Updated as many warnings as I can find
=> FHB 381 Fix SD AcceptanceTests warnings

src/Directory.Packages.props, src/ui/connect-ui/src/FamilyHubs.Referral.Infrastructure/DistributedCache/ConnectionRequestDistributedCache.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ContactDetails.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/StartupExtensions.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.IntegrationTests/BaseTest.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.IntegrationTests/PerformanceData/ConnectTest.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Areas/AccountAdmin/ManagePermissions/EditTests.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Areas/VcsAdmin/AddOrganisationCheckDetailsTests.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Areas/VcsAdmin/AddOrganisationTests.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Areas/VcsAdmin/ViewOrganisationTests.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests.csproj, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Core/Exceptions/ApiException.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/Edit.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/EditEmail.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/EditEmailChangedConfirmation.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/EditRolesChangedConfirmation.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/Pages/AddOrganisationCheckDetails.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/Pages/ManageOrganisations.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/Pages/ViewOrganisation.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/FamilyHubs.ServiceDirectory.Admin.Web.csproj, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Locations-For-Service.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Service-Detail.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Program.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/StartupExtensions.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/ViewModel/InputPageViewModel.cs
Fix warnings in Manage UI.
Also contains:
* set direct nuget package vulnerability checking globally (at least for the time being)
* some bonus tidy ups in Connect UI
=> FHB-381 Fix admin UI warnings

src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Core/Commands/Organisations/CreateOrganisation/CreateOrganisationCommand.cs, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Core/Commands/Services/UpdateService/UpdateServiceCommand.cs, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Core/Queries/Services/GetServices/GetServicesCommand.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Api.FunctionalTests/BaseWhenUsingApiUnitTests.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Api.FunctionalTests/TestDataProvider.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Api.FunctionalTests/WhenGettingApiInfoUnitTest.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Api.FunctionalTests/WhenUsingLocationApiUnitTests.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Api.FunctionalTests/WhenUsingOrganisationApiUnitTests.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Api.FunctionalTests/WhenUsingServiceApiUnitTests.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Api.FunctionalTests/WhenUsingTaxonomiesApiUnitTests.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Core.IntegrationTests/Services/WhenValidatingServiceCommands.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.IntegrationTests/PerformanceData/ConnectTest.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.IntegrationTests/PerformanceData/FindTest.cs
- Fix build warnings for SD integration and functional tests
=> Fhb 381 fix sd test warnings

.github/workflows/deploy.yml
Add Test2 to the pipeline for this release
=> Add Test2 to the release

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml.cs
Add the redirect to the page.
The page is in another PR https://github.com/DFE-Digital/fh-services/pull/126 and will exist once merged together
=> Add redirects to error page when there is open connections.

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml
Ticket: [FHB-672](https://dfedigital.atlassian.net/browse/FHB-672)
---
It turns out the prototype accidentally had two variants of the same page and I used the older one for the ticket, so this is a quick fix to just get that corrected to the right one!
[FHB-672]: https://dfedigital.atlassian.net/browse/FHB-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-672 : Fix Wording

README.md, docs/hsds-3_0-er-diagram.md, src/service/notification-api/src/FamilyHubs.Notification.Data/FamilyHubs.Notification.Data.csproj, src/ui/connect-dashboard-ui/src/FamilyHubs.RequestForSupport.Web/FamilyHubs.RequestForSupport.Web.csproj, src/ui/connect-ui/src/FamilyHubs.Referral.Infrastructure/FamilyHubs.Referral.Infrastructure.csproj, src/ui/connect-ui/src/FamilyHubs.Referral.Web/FamilyHubs.Referral.Web.csproj, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Core/FamilyHubs.ServiceDirectory.Admin.Core.csproj
* docs: add er diagram
* docs: swap to MD
* docs: show in readme
* docs: add missing relationship
* docs: fix mysterious space char...
* docs: update hsds-3_0-er-diagram.md
* docs: fix readme
* fix: notification packages as proj references
---------
=> FHB-725: Fix Notifications Core/Client package references (#137)

README.md, docs/hld.md, src/service/idam-api/src/FamilyHubs.Idam.Api/appsettings.json
Adds a slimmed-down version of the existing High Level Design document in Sharepoint/Confluence. The idea is to add code-/arch-related documentation from Sharepoint and Confluence into the repo. This means we can update the relevenat docs alongside our other work, and include it as part of our definition of done.
=> FHB-724 Add High Level Design document

src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Add/AddAccountCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Add/AddClaimCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Add/AddUserSessionCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Delete/DeleteAccountCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Delete/DeleteAllUserSessionsCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Delete/DeleteClaimCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Delete/DeleteExpiredUserSessionsCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Delete/DeleteOrganisationAccountsCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Delete/DeleteUserSessionCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Update/UpdateAccountCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Update/UpdateAccountSelfServiceCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Update/UpdateClaimCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Commands/Update/UpdateUserSessionCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/DataIntegrationTestBase.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/FamilyHubs.Idam.Core.IntegrationTests.csproj, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Queries/GetAccountClaims/GetAccountClaimsByEmailCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Queries/GetAccounts/GetAccountsCommandTests.cs, src/service/idam-api/tests/FamilyHubs.Idam.Core.IntegrationTests/Queries/GetUserSession/GetUserSessionCommandTests.cs
Ticket: [FHB-736](https://dfedigital.atlassian.net/browse/FHB-736)
---
Convert Moq -> NSubstitute for IdAM API
[FHB-736]: https://dfedigital.atlassian.net/browse/FHB-736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-736 : IdAM API

src/service/notification-api/tests/FamilyHubs.Notification.IntegrationTests/DataIntegrationTestBase.cs, src/service/notification-api/tests/FamilyHubs.Notification.IntegrationTests/FamilyHubs.Notification.IntegrationTests.csproj, src/service/notification-api/tests/FamilyHubs.Notification.IntegrationTests/WhenCreatingNotifications.cs, src/service/notification-api/tests/FamilyHubs.Notification.UnitTests/BaseCreateDbUnitTest.cs, src/service/notification-api/tests/FamilyHubs.Notification.UnitTests/FamilyHubs.Notification.UnitTests.csproj, src/service/notification-api/tests/FamilyHubs.Notification.UnitTests/WhenGettingSentNotifications.cs, src/service/notification-api/tests/FamilyHubs.Notification.UnitTests/WhenUsingGovNotifyCommands.cs, src/service/notification-api/tests/FamilyHubs.Notification.UnitTests/WhenUsingGovNotifySender.cs, src/service/notification-api/tests/FamilyHubs.Notification.UnitTests/WhenValidatingNotificationCommands.cs
Ticket: [FHB-736](https://dfedigital.atlassian.net/browse/FHB-736)
---
- Convert Moq -> NSubstitute for Notification API
- Refactor & Cleanup Code
[FHB-736]: https://dfedigital.atlassian.net/browse/FHB-736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-736 : Notification API

terraform/modules/fhinfrastructurestack/fh-report-api-app.tf, terraform/modules/fhinfrastructurestack/fh-report-stg-api-app.tf, terraform/modules/fhinfrastructurestack/main.tf, terraform/modules/fhinfrastructurestack/open-referral-func.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-722
- Removed all existing IP restriction blocks that allowed users access to backend APIs
- Added restriction block to deny public access
- Created a document to explain how to add IPs: https://dfedigital.atlassian.net.mcas.ms/wiki/spaces/FHGUW/pages/4718133249/Application+Services
=> FHB-722 Remove Public Access to APIs

src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/ClientHelper.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingIdamsClient.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingOrganisationClientService.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingReferralClientService.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Core/ValidationAttributes/UKGdsPostcodeAttributeTests.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Core/ValidationAttributes/UKGdsTelephoneNumberAttributeTests.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/FamilyHubs.ReferralUi.UnitTests.csproj, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Helpers/TestHelpers.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Infrastructure/DistributedCache/ReferralDistributedCacheTests.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Services/BaseClientService.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingOpenReferralOrganisationClientService.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/BaseProfessionalReferralPage.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingCheckDetails.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingConsent.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingContactByPhone.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingContactDetails.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingContactMethods.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingEmail.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingLetter.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingLocalOfferDetail.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingSafeguardingModel.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingSearch.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingSharePrivacy.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingSupportDetails.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingTelephone.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingText.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingWhySupport.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/WhenUsingConnectTelemetryPiiRedactor.cs
- Updated all tests to use NSubstitute, replacing Moq.
- Updated some duplicate code and tests
=> FHB-736: connect UI Nsubstitute

src/ui/connect-dashboard-ui/tests/FamilyHubs.RequestForSupport.UnitTests/BaseWhenUsingPage.cs, src/ui/connect-dashboard-ui/tests/FamilyHubs.RequestForSupport.UnitTests/FamilyHubs.RequestForSupport.UnitTests.csproj, src/ui/connect-dashboard-ui/tests/FamilyHubs.RequestForSupport.UnitTests/Helpers/TestHelpers.cs, src/ui/connect-dashboard-ui/tests/FamilyHubs.RequestForSupport.UnitTests/WhenUsingGetRequestIdModel.cs, src/ui/connect-dashboard-ui/tests/FamilyHubs.RequestForSupport.UnitTests/WhenUsingReferralClientService.cs, src/ui/connect-dashboard-ui/tests/FamilyHubs.RequestForSupport.UnitTests/WhenUsingTheVCSDashboard.cs, src/ui/connect-dashboard-ui/tests/FamilyHubs.RequestForSupport.UnitTests/WhenUsingTheVcsDetailsPage.cs
Change from Moq to NSubstitute
Added a TODO for a shared unit test library but decided to wait to see how the rest of the projects look before creating an abstraction
=> FHB-736: connect dashboard UI

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/delete-service.cshtml.cs
Ticket: [FHB-871](https://dfedigital.atlassian.net/browse/FHB-871)
---
This PR:
- Redirects to a 404 "Page not found" page when trying to access the delete a service page for a service that has already been deleted
- In effect this means the browser back button, or pasting the URL, can't "break" the deletion journey by letting you select the options again even if you've already deleted a service.
- Also I swapped the order of the `OnGet` and the `OnPost` in the code because it was keeping me up at night
[FHB-871]: https://dfedigital.atlassian.net/browse/FHB-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-871 : Deleting Deleted Services

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Shared/_DeleteServiceErrorVcfsAdmin.cshtml
Ticket: [FHB-671](https://dfedigital.atlassian.net/browse/FHB-671)
---
This PR:
- Changes the VCFS redirect again
[FHB-671]: https://dfedigital.atlassian.net/browse/FHB-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-671 : Re-Re-Redirect

.github/workflows/build-and-test-template.yml, .github/workflows/build-and-test.yml, src/Directory.Packages.props, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Api.FunctionalTests/FamilyHubs.ServiceDirectory.Api.FunctionalTests.csproj, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Core.IntegrationTests/FamilyHubs.ServiceDirectory.Core.IntegrationTests.csproj
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-361
- Added pre-requisites for ubuntu that run for a specific project e.g. service directory api
- Added csproj blocks to conditionally add packages for the platform
=> FHB-361: Service directory ubuntu tests

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-locations/Location-Information-Content.cshtml
Update to Location-Information-Content.cshtml
Small change to add a location journey in oder to address issue flagged by Salford VCFSs.
=> FHB-859: Manage update: adding location details as part of add a service (Salford)

src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Mappers/ServiceMapper.cs, src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/ServiceDetail/Index.cshtml, src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/ServiceDetail/Index.cshtml.cs, src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/ServiceFilter/_Service.cshtml, src/ui/find-ui/tests/FamilyHubs.ServiceDirectory.UnitTests/Services/ServiceMapperTests.cs, src/ui/find-ui/tests/FamilyHubs.ServiceDirectory.UnitTests/Web/WhenUsingServiceDetailModel.cs
- Added dl tag to contact list
- added a hide clause to all fields in service description page
- added 'years old' to age range field
=> feat: FHB-944  find additional changes

src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/ServiceDetail/Index.cshtml
Added a title to the service details page
=> fix: FHB-952 - Add page title to service details page

src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/Index.cshtml, src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/PostcodeSearch/index.cshtml, test/k6/README.md, test/k6/env/local/config.load.json, test/k6/env/local/config.soak.json, test/k6/env/local/config.stress.json, test/k6/main.js, test/k6/tests/find-tests.js
Added the scenarios we need to test find.
The tests are flaky as we do not have ids on some locators, need ticket: https://dfedigital.atlassian.net/browse/FHB-912 to be completed.
Test run scheduled for Dec 11th - locators to be updated then.
=> FHB-634: Finalise Find performance Tests

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/Pages/ViewOrganisation.cshtml
Ticket: [FHB-678](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-678)
---
This PR:
- Fixes an issue where sorting the list of services looked to have a random order instead of alphabetical
[FHB-678]: https://dfedigital.atlassian.net/browse/FHB-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-678 : Fix Sorting

terraform/modules/fhinfrastructurestack/main.tf, terraform/modules/fhinfrastructurestack/monitoring.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-986
Added new app insights resource
=> FHB-986: Added new app insights resource

.github/actions/variable-substitution/action.yml, src/function/open-referral-function/src/FamilyHubs.OpenReferral.Function/appsettings.json, src/service/idam-api/src/FamilyHubs.Idam.Api/appsettings.json, src/service/notification-api/src/FamilyHubs.Notification.Api/appsettings.json, src/service/referral-api/src/FamilyHubs.Referral.Api/appsettings.json, src/service/report-api/src/FamilyHubs.Report.Api/appsettings.json, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/appsettings.json, src/ui/connect-dashboard-ui/src/FamilyHubs.RequestForSupport.Web/appsettings.json, src/ui/connect-ui/src/FamilyHubs.Referral.Web/appsettings.json, src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/appsettings.json, src/ui/idam-maintenance-ui/src/FamilyHubs.Idams.Maintenance.UI/appsettings.json, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/appsettings.json, terraform/modules/fhinfrastructurestack/fh-report-api-app.tf, terraform/modules/fhinfrastructurestack/main.tf, terraform/modules/fhinfrastructurestack/open-referral-func.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-987
Update to use new single app insights instance and correct connection string.
=> FHB-987: Update to use new single app insights

terraform/modules/fhinfrastructurestack/fh-report-api-app.tf, terraform/modules/fhinfrastructurestack/main.tf, terraform/modules/fhinfrastructurestack/open-referral-func.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-988
- Remove redundant app insights now we have a single app insights with all environments configured to use it
=> FHB-988: Remove redundant app insights

.github/workflows/build-and-test-template.yml
Fix an issue in the pipeline where a ubuntu package is no longer being found. Not an issue we introduced
=> ci: fix ubuntu package issue

src/Directory.Packages.props, src/service/idam-api/src/FamilyHubs.Idam.Api/Program.cs, src/service/idam-api/src/FamilyHubs.Idam.Api/appsettings.json, src/service/notification-api/src/FamilyHubs.Notification.Api/Program.cs, src/service/notification-api/src/FamilyHubs.Notification.Api/appsettings.json, src/service/referral-api/src/FamilyHubs.Referral.Api/Program.cs, src/service/referral-api/src/FamilyHubs.Referral.Api/appsettings.json, src/service/report-api/src/FamilyHubs.Report.Api/Program.cs, src/service/report-api/src/FamilyHubs.Report.Api/appsettings.json, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/Program.cs, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/appsettings.json, src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/Extensions/StartupExtensions.cs, src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/FamilyHubs.SharedKernel.csproj, src/shared/shared-kernel/tests/fh-shared-kernel.unit-tests/Extensions/StartupExtensions/KeyVaultTests.cs, src/ui/connect-dashboard-ui/src/FamilyHubs.RequestForSupport.Web/Program.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Program.cs, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Extensions/StartupExtensions/KeyVaultTests.cs
Added to SharedKernal and tested the Prefix.
Added to all projects that have appsettings that can pull from keyvault
=> feat: FHB-967 Add KeyVault to Startup

terraform/modules/fhinfrastructurestack/main.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-965
- Add app secret permissions on the admin key vault
- Refactor all perms to use locals
=> FHB-965: Add app secret permissions on the admin key vault

.github/workflows/build-and-test-template.yml, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Pages/manage-services/WhenWhatLanguageOnGetIsCalled.cs, src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Pages/manage-services/WhenWhatLanguageOnPostIsCalled.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Core/Models/JourneyCacheModel.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/What-Language.cshtml.cs
Unit tests to support some of the refactoring I did on the non UI elements. Also support the bug fix in previous PR
=> test: FHB-113  unit tests

.github/workflows/run-acceptance-tests.yml
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-972
- Fix acceptance tests to pull config from correct key vault
=> FHB-972: Fix incorrect key vault identifier

src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Pages/welcome/WhenOnGetIsCalled.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Welcome.cshtml, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Welcome.cshtml.cs
Moved a heading to a caption as per DAC recommendation.
Updated logic to change the Heading and caption  text based on role
Added a description to the page.
Added horizontal rules as per prototype design.
Added Unit tests to support changes.
=> feat: FHB-115  dac manage headings

src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Errors/PossibleErrors.cs, src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/PostcodeSearch/index.cshtml, src/ui/find-ui/src/FamilyHubs.ServiceDirectory.Web/Pages/PostcodeSearch/index.cshtml.cs
Refactor postcode search errors to use ErrorState
=> feat(Find): Update page title when showing error state

terraform/modules/fhinfrastructurestack/fh-report-stg-api-app.tf, terraform/modules/fhinfrastructurestack/main.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1032
- Enable auditing to both the app and reporting sql server
- Send auditing to log analytics
=> FHB-1032: SQL Server auditing

src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Pages/welcome/WhenOnGetIsCalled.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Welcome.cshtml.cs
Update to the AC means the text in the header has changed.
=> feat: Update Manage heading text for new AC

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/Pages/ManageOrganisations.cshtml, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/_ViewImports.cshtml
Ticket: [FHB-998](https://dfedigital.atlassian.net/browse/FHB-998)
---
This PR:
- Adds the organisation name filter to the mobile view
[FHB-998]: https://dfedigital.atlassian.net/browse/FHB-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-998 : Allow LA Admins to View VCFS Services in Manage (Mobile View)

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/VcsAdmin/Pages/ManageOrganisations.cshtml
Ticket: [FHB-998](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-998)
---
This PR:
- Changes occurrences of "filters" to "filter" on the Organisations dashboard 
[FHB-998]: https://dfedigital.atlassian.net/browse/FHB-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FHB-998 : Fix Typo

src/Directory.Packages.props, src/service/idam-api/src/FamilyHubs.Idam.Api/web.config, src/service/mock-hsda-api/src/FamilyHubs.Mock-Hsda.Api/web.config, src/service/notification-api/src/FamilyHubs.Notification.Api/web.config, src/service/referral-api/src/FamilyHubs.Referral.Api/web.config, src/service/report-api/src/FamilyHubs.Report.Api/web.config, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/web.config
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1031
- Add content security policy to allow the inline swagger ui elements to render correctly
=> FHB-1031: Add alternative content security policy for Swagger

docs/hld.md
Very small update to the HLDD to add Pre-Prod to the environment list.
=> chore: Update HLDD

.github/workflows/sonarcloud.yml, src/function/open-referral-function/src/FamilyHubs.OpenReferral.Function/Repository/FunctionDbContext.cs, src/service/mock-hsda-api/src/FamilyHubs.Mock-Hsda.Api/FamilyHubs.Mock-Hsda.Api.csproj, src/shared/shared-kernel/examples/GovSignInExample/GovSignInExample/GovSignInExample.csproj, src/shared/shared-kernel/examples/GovSignInExample/SecureApiExample/SecureApiExample.csproj, src/shared/web-components/example/FamilyHubs.Example/FamilyHubs.Example.csproj, src/ui/idam-maintenance-ui/src/FamilyHubs.Idams.Maintenance.Core/FamilyHubs.Idams.Maintenance.Core.csproj, src/ui/idam-maintenance-ui/src/FamilyHubs.Idams.Maintenance.Data/FamilyHubs.Idams.Maintenance.Data.csproj, src/ui/idam-maintenance-ui/src/FamilyHubs.Idams.Maintenance.UI/FamilyHubs.Idams.Maintenance.UI.csproj
Ticket: [FHB-798](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-798)
- ADR : [Confluence](https://dfedigital.atlassian.net.mcas.ms/wiki/spaces/FHGUW/pages/3725262849/Architecture+Decision+Record+ADR) (No. 25 - 10/12/2024)
- DevOps Documentation: [Confluence](https://dfedigital.atlassian.net/wiki/spaces/FHGUW/pages/4936138778/Pipelines#SonarCloud)
---
This PR:
- Excludes "Migrations" folders from test coverage
- Excludes "Migrations" from build analysis (code smells, code duplication, et al.)
- Excludes the Mock HSDA API project from all analysis, as this project isn't production code / user facing
- Excludes various "Example" projects from a couple of places, as these aren't production code / user facing
[FHB-798]: https://dfedigital.atlassian.net/browse/FHB-798?atlOrigin=eyJpIjoiNWR …
=> FHB-798 : Exclusions

.github/actions/database-migration/action.yml, .github/workflows/deploy-service.yml
- Post merge fix to re-add missing key vault prefixes for the deployment pipeline
=> Fix pipeline key vault prefix

terraform/modules/fhinfrastructurestack/main.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1036
- Enable key vault purge protection and delete redundant key vaults
=> feat(terraform): Enable key vault purge protection

test/manage-e2e-tests /.gitignore, test/manage-e2e-tests /README.md, test/manage-e2e-tests /package-lock.json, test/manage-e2e-tests /package.json, test/manage-e2e-tests /playwright.config.ts, test/manage-e2e-tests /tests/manage-testing.spec.ts, test/manage-e2e-tests /tests/serenity-tools/gov-login-page-objects.ts, test/manage-e2e-tests /tests/serenity-tools/login-tasks.ts, test/manage-e2e-tests /tests/serenity-tools/manage-index.ts, test/manage-e2e-tests /tests/serenity-tools/manage-questions.ts
First PR to add manage test suite and setup steps for logging into test environment and logging into manage as a DFE admin user.
Had to use CSS selector for gov one login components as we have no control over them.
2 more PRs to follow where I will add the test data for these particular tests and the actual tests.
Existing test written pass on Chrome and Edge, known issue on firefox hence failure (bug raised FHB-1008)
=> FHB-1113: E2E Automated Tests: Adding Users in Manage as Dfe Admin

terraform/main.tf, terraform/modules/fhinfrastructurestack/monitoring.tf, terraform/modules/fhinfrastructurestack/vars.tf, terraform/pre-production.tfvars, terraform/production.tfvars, terraform/vars.tf
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1146
- Set sensible log retention lengths based upon the GDS guide and what we can actually achieve based upon constraints of the resources
=> chore(terraform): Update log retention to match GDS guidance

terraform/modules/fhinfrastructurestack/dashboard/template.json
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1145
- Added ADF status to the dashboard template
=> FHB-1145: Add ADF to dashboard

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Time-Details-At-Location.cshtml.cs
Small bonus Tina found while testing
=> [FHB-856] Fix another bug with error states in manage service flow

test/e2e-seed-data-framework/scripts/seed/seed-service-directory-db.js
Added code to seed location data which is required to create a service
* added seed data for test location named Test Location
=> FHB-1183: Adding Location Seeding Data 

src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250122102655_programIdNullable.Designer.cs, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250122102655_programIdNullable.cs, src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Service.cs
fix(deds): programId nullable
Make Service.ProgramId nullable. Services do not require it.
There is a bug ticket FHB-1266 for information but this is not aimed at a release yet.
=> fix(deds): programId nullable

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Search.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Search.cshtml.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/_SearchPractitionerUser.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/_SearchPublicUser.cshtml, src/ui/connect-ui/tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingSearch.cs
Ticket: [FHB-1247](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1247)
---
This PR:
- Adds a variation of the postcode search page for non-authenticated public users
[FHB-1247]: https://dfedigital.atlassian.net/browse/FHB-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(connect): FHB-1247 - Search Page Content

src/shared/web-components/src/FamilyHubs.SharedKernel.Razor/Pages/Shared/_SingleAutocompletePage.cshtml
Added Continue test data id to the _SingleAutocompletePage.cshtml file for the automation E2E tests
=> FHB1183-add-continue-button

src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Api/Program.cs
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1228Fix slow first postcode search by warming up the Entity Framework AutoMapper configuration upon start up
=> chore: Fix slow first postcode search

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/Error/403.cshtml, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/Error/403.cshtml, terraform/modules/fhinfrastructurestack/errorpages/referral_ui/dev/error403.html, terraform/modules/fhinfrastructurestack/errorpages/referral_ui/preprod/error403.html, terraform/modules/fhinfrastructurestack/errorpages/referral_ui/prod/error403.html, terraform/modules/fhinfrastructurestack/errorpages/referral_ui/test/error403.html, terraform/modules/fhinfrastructurestack/errorpages/referral_ui/test2/error403.html, terraform/modules/fhinfrastructurestack/errorpages/sd_admin_ui/dev/error403.html, terraform/modules/fhinfrastructurestack/errorpages/sd_admin_ui/preprod/error403.html, terraform/modules/fhinfrastructurestack/errorpages/sd_admin_ui/prod/error403.html, terraform/modules/fhinfrastructurestack/errorpages/sd_admin_ui/test/error403.html, terraform/modules/fhinfrastructurestack/errorpages/sd_admin_ui/test2/error403.html
Updated for connect and manage
403 doesn't exist for find
Connect dashboard is already merged in another branch so changing that would just create conflicts
=> [FHB-1251] Update 403 content

src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250123144453_dedsApplicationProcess.Designer.cs, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250123144453_dedsApplicationProcess.cs, src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Repository/OpenReferralDbContextExtension.cs
ApplicationProcess is a description field and could contain much more than 512 characters. We can't predict the length to have a fixed length.
=> fix(deds): ApplicationProcess

src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250123142248_minAndMaxAgeToNullable.Designer.cs, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250123142248_minAndMaxAgeToNullable.cs, src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Service.cs
Make min and max age nullable as per HSDS 3.0 schema
=> Fix(deds): fhd 54 min max age nullable

docs/arch/Generate-AdrIndex.ps1, docs/arch/README.md
Used PowerShell after seeing its usage also in GitHub actions workflows.
=> Add ADR summary generation script and initial summary table

src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Pages/manage-services/Locations-For-Service.cshtml
Added test id for location page
=> FHB-1153: Add continue button for add location page

test/find-e2e-tests/playwright.config.ts
- Fix e2e find tests not launching project because of dependency issue
- Tested against dev to ensure they run green
=> chore: Fix e2e find tests

src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Core/Queries/Organisations/GetOrganisationById/GetOrganisationByIdCommand.cs, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Core/Queries/Services/GetServices/GetServicesCommand.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Core.IntegrationTests/DataIntegrationTestBase.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Core.IntegrationTests/Services/WhenUsingGetServiceCommand.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Core.IntegrationTests/TestDataProvider.cs, src/shared/service-directory-shared/src/FamilyHubs.ServiceDirectory.Shared/Dto/ServiceDto.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Core/ApiClients/OrganisationClientService.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferResults.cshtml
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1245
- Add organisation name to the service details
- Fix tests to handle post-AutoMapper setting of the org name
=> feat: Add organisation name to the service DTO for displaying

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
I don't think you can currently populate this field but it's shown in the design.
=> [FHB-1248] Add accessibility details row to locations

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/Index.cshtml
Ticket: [FHB-1276](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1276)
---
This PR:
- Replaces the placeholder start page with the proper Single Directory start page.
[FHB-1276]: https://dfedigital.atlassian.net/browse/FHB-1276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Connect): FHB-1276 - Start Page

docs/arch/ADR026-merge-find-into-connect.md, docs/arch/ADR026.md, docs/arch/README.md
Retroactive ADR to capture the reasoning for the merge/find component changes 
i.e. why merge find into connect?
Please view the ADR in markdown preview mode for the best reading experience.
=> ADR026 - Merge Find into Connect

src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250206162130_DedsServiceChecksum.Designer.cs, src/service/service-directory-api/src/FamilyHubs.ServiceDirectory.Data/Migrations/20250206162130_DedsServiceChecksum.cs, src/shared/shared-kernel/src/fh-shared-kernel.shared-kernel/OpenReferral/Entities/Service.cs
Adds a Checksum field to the database.
Next work is to populate and use the checksum field
=> feat(deds): Add checksum field and migration

docs/arch/ADR026-merge-find-into-connect.md, docs/arch/README.md, test/manage-e2e-tests/playwright.config.ts, test/manage-e2e-tests/tests/auth.setup.ts, test/manage-e2e-tests/tests/helpers.ts, test/manage-e2e-tests/tests/serenity-tools/questions/login-questions.ts
Post-release merge of `release-manage-back-button`
=> Merge `main` into `data-stream` 

src/shared/service-directory-shared/src/FamilyHubs.ServiceDirectory.Shared/Dto/ServiceDto.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferResultsPartialViews/_ResultsSection.cshtml
Move distance out of link
Remove double margin on categories
Remove service deliveries section
=> [FHB-1086] Ticket fixes

src/ui/manage-ui/Test/FamilyHubs.ServiceDirectory.Admin.Web.UnitTests/Areas/AccountAdmin/ManagePermissions/EditRolesTests.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/DeleteUser.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/Edit.cshtml.cs, src/ui/manage-ui/src/FamilyHubs.ServiceDirectory.Admin.Web/Areas/AccountAdmin/Pages/ManagePermissions/EditRoles.cshtml.cs
Merge into main for regression testing
=> Release manage user bugs

terraform/modules/fhinfrastructurestack/alerting.tf
We need to terraform the following ADF alerts (all at severity 1 - error):
Failed Pipeline Runs (total over 30 minutes > 0, check every 1 minute)
=> FHB-1242 Add ADF failed pipeline runs alert

test/e2e-seed-data-framework/scripts/seed/seed-service-directory-db.js
Added data seeding for LA and VCFS services so we can write E2E tests for single directory.
=> FHB-1254-E2E Test Automation: Data Seeding For Single Directory

terraform/modules/fhinfrastructurestack/alerting.tf
Descope alerts for the open referral function app. Revisit as part of data stream work
=> FHB-1241 Removed the alerts for the open_referral_function_app

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
Ticket: [FHB-1337](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1337)
[FHB-1337]: https://dfedigital.atlassian.net/browse/FHB-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Connect): FHB-1337 - Remove Accessibility Details Section

test/e2e-seed-data-framework/scripts/seed/seed-service-directory-db.js
Added westminster admin area code and postcode to seeded location and orgs.
Fixed typo.
=> FHB-1174-Public user E2E tests - View and Select Services

src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Core.IntegrationTests/Services/WhenUsingGetServiceCommand.cs, src/service/service-directory-api/tests/FamilyHubs.ServiceDirectory.Core.IntegrationTests/TestDataProvider.cs, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs
Ticket: [FHB-1370](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1370)
This PR:
- Updates the "19 to 24 years with SEND" to "19 to 25 years with SEND"
- Consequently ensures that "25+" results come back
[FHB-1370]: https://dfedigital.atlassian.net/browse/FHB-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Connect): FHB-1370 - Update the Age Category

src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/Accessibility/Index.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/Shared/_CookiePolicy.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/privacy/Index.cshtml, src/ui/connect-ui/src/FamilyHubs.Referral.Web/Pages/terms-and-conditions/Index.cshtml
This PR:
- Updates the Accessibility, Cookies, Privacy and Terms & Conditions pages to bring them up to date with the new content for the Single Directory MVP.
Ticket: [FHB-1418](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1418)
Ticket: [FHB-1419](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1419)
Ticket: [FHB-1421](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1421)
Ticket: [FHB-1422](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1422)
[FHB-1418]: https://dfedigital.atlassian.net/browse/FHB-1418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FHB-1419]: https://dfedigital.atlassian.net/browse/FHB-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FHB-1421]: …
=> feat(Connect): Update Footer Pages Content

docs/infrastructure/github-secrets-and-variables.md
Hint: View in rich-diff mode :slightly_smiling_face:
Ticket: [FHB-1474](https://dfedigital.atlassian.net.mcas.ms/browse/FHB-1474)
This PR...
- Creates a document pertaining to the GitHub Secrets & Variables.
- Lists out each item at each level, what it's used for, what workflows they are apart of, and in the case of Environment variables which environments they apply to.
[FHB-1474]: https://dfedigital.atlassian.net/browse/FHB-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: FHB-1474 - Document GitHub Secrets & Variables
